version: '3'
services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: estados_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  shp-importer:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: estados_db
    volumes:
      - ./estados:/data/estados

volumes:
  pgdata:
